spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jxauca?useUnicode = true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: 1234
# mybaits配置文件
mybatis:
  type-aliases-package: com.zmx.jxauca.entity
  mapper-locations: classpath*:com/zmx/jxauca/mapper/*.xml